library(dplyr)
library(tidyverse)
library(lubridate)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile= "C:/Users/Admin/OneDrive/Bureau/Coursera/Data Science Specialization/Exploratory Data Analysis/Week 1/Swirl and quiz/db.zip")
db<- read.table("db/household_power_consumption.txt", sep= ";", header = TRUE)
head(db)
db$Date <- as.Date(db$Date, "%d/%m/%Y")
Feb <- subset(db, db$Date == c("2007-02-01","2007-02-02"))
Feb <- Feb %>%
  unite(col = "datetime", c(Date, Time)) 
Feb[,1] <- ymd_hms(Feb[,1]) 
Feb$Global_intensity <- as.numeric(Feb$Global_intensity)
Feb$Sub_metering_1 <- as.numeric(Feb$Sub_metering_1)
Feb$Sub_metering_2 <- as.numeric(Feb$Sub_metering_2)
Feb$Sub_metering_3 <- as.numeric(Feb$Sub_metering_3)
Feb$Global_intensity <- as.numeric(Feb$Global_intensity)
Feb$Global_reactive_power <- as.numeric(Feb$Global_reactive_power)

png("plot4.png", width= 480, height= 480, units= "px")
par(mfrow= c(2,2))
with(Feb, plot(Feb$`datetime`, Global_active_power, type="l", col="black", xlab= "", ylab= "Global Active Power"))
with(Feb, plot(Feb$`datetime`, Voltage, type="l", col="black", xlab= "", ylab= "Voltage"))
with(Feb, plot(Feb$`datetime`, Feb$Global_intensity, type="n", col="black", xlab= "", ylab= "Energy sub metering"))
with(Feb, lines(Feb$`datetime`, Sub_metering_1, col="black"))
with(Feb, lines(Feb$`datetime`, Sub_metering_2, col="red"))
with(Feb, lines(Feb$`datetime`, Sub_metering_3, col="blue"))
legend("topright", col= c("black", "red", "blue"), legend= c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty= 1)
with(Feb, plot(Feb$`datetime`, Global_reactive_power, type="l", col="black", xlab= "", ylab= "Global_reactive_power"))
dev.off()
?legend
